spring:
  profiles: development
conf:
  name: test-YAML
  environment: test
  servers:
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
  profiles: prod
conf:
  name: prod-YAML
  environment: production
  servers:
    - www.abc.com
    - www.xyz.com
